name: 'TEMPORARY LANDING!'
favicon: null
layout_spectrum: 0.49781
typography_spectrum: 0.87405
title: RVP BLOG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.16658542584627867
  lightness: 0.16267088637687266
  saturation: 0.30871845525689423
  rhythmicContrast: 0.20953972055576742
purpose: []
